# Generated by Django 3.0.7 on 2020-08-29 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='aucune', max_length=150, null=True)),
                ('isMissing', models.BooleanField(default=0, null=True)),
                ('Date', models.DateTimeField(default='00:00', null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.Student')),
            ],
        ),
    ]
